### ISSUE TITLE
Free service not working

### ISSUE THREAD

**Issue by anewuser** [NicolasLM/feedsubs#321]
Hello. I tried adding a few feeds to test the service, but nothing happened. Then I tried uploading the sample OPML file from `https://opml-gen.ovh/`, and got a `500 - Internal server error` message.

**Comment by NicolasLM** [comment]
Hi, thank you for letting me know.

1. I know this is not the most user friendly but adding a new feed is done in the background and it can take a while for the new feed to appear on your profile.
2. I think your OPML file was invalid, could you post a sample of it?

**Comment by anewuser** [comment]
Maybe you could add a message to tell users that the feeds are still being processed.

I just downloaded the file again now and saw that it mixes up `'` with `"`. Maybe that was the cause of the problem. Or maybe your parser expects more attributes. Anyway, their files have worked with other feed importers.

`subscriptions.xml`

```
<opml version="2.0">
	<body>
		<outline text="Subscriptions" title="Subscriptions">
			<outline xmlUrl='http://www.theverge.com/rss/index.xml' />
                        <outline xmlUrl='https://techcrunch.com/feed/' />
                        <outline xmlUrl='http://feeds.mashable.com/Mashable' />
                        <outline xmlUrl='http://www.engadget.com/rss.xml' />
		</outline>
	</body>
</opml>

```

[subscriptions.zip](https://github.com/NicolasLM/feedsubs/files/4898130/subscriptions.zip)
